baseUrl: https://www.adityakonarde.com/
languageCode: en-us
theme: PaperMod
copyright: '2024 Aditya Konarde'
pagination:
  pagerSize: 5
services:
  googleAnalytics:
    ID: "G-32YZMDJ7FF" 

params:
  profileMode:
    enabled: true
    title: "Aditya Konarde"
    subtitle: "Engineering Leader | Technology Enthusiast | Photographer"
    imageUrl: "images/propic-square.jpeg"
    imageTitle: "Aditya Konarde"
    imageWidth: 200
    imageHeight: 200
    buttons:
      - name: "About"
        url: "about"
      - name: "Blog"
        url: "posts"
      - name: "Contact"
        url: "https://www.linkedin.com/in/adityakonarde/"

  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/adityakonarde/"
    - name: "github"
      url: "https://github.com/aditya-konarde"
    - name: "twitter"
      url: "https://twitter.com/aditya_konarde"
    - name: "instagram"
      url: "https://instagram.com/aditya.konarde"

  # Theme settings
  defaultTheme: auto
  disableThemeToggle: false
  showMenuItems: 4

  # Search configuration
  search:
    enable: true
    type: "fuse"
    fuseOptions:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 100
      threshold: 0.4
      minMatchCharLength: 2

languages:
  en:
    title: Aditya Konarde's Blog
    params:
      subtitle: ''
      keywords: ''
      menuMore: Show more
      writtenBy: Written by
      readMore: Read more
      readOtherPosts: Read other posts
      newerPosts: Newer posts
      olderPosts: Older posts
      dateFormatSingle: 2006-01-02
      dateFormatList: 2006-01-02
      logo:
        logoText: Aditya Konarde
        logoHomeLink: /
    
    menu:
      main:
      - identifier: about
        name: About
        url: /about
      - identifier: Blog
        name: Blog
        url: /posts
