baseUrl: https://www.adityakonarde.com/
languageCode: en-us
theme: hello-friend
copyright: '2024 Aditya Konarde'
pagination:
  pagerSize: 5
services:
  googleAnalytics:
    ID: "G-32YZMDJ7FF" 

params:
  # dir name of your blog content (default is `content/posts`)
  contentTypeName: posts
  # "dark" or "light"
  defaultTheme: light
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems: 4

languages:
  en:
    title: Aditya Konarde's Blog
    params:
      subtitle: ''
      keywords: ''
      menuMore: Show more
      writtenBy: Written by
      readMore: Read more
      readOtherPosts: Read other posts
      newerPosts: Newer posts
      olderPosts: Older posts
      dateFormatSingle: 2006-01-02
      dateFormatList: 2006-01-02
      logo:
        logoText: Aditya Konarde
        logoHomeLink: /
    
    menu:
      main:
      - identifier: Contact
        name: Contact
        url: https://calendly.com/aditya-konarde
      - identifier: about
        name: About
        url: /about
      - identifier: Blog
        name: Blog
        url: /posts
      - identifier: Photography
        name: Photography
        url: https://www.instagram.com/aditya.konarde

