baseUrl: https://www.adityakonarde.com/
languageCode: en-us
theme: PaperMod
copyright: '2024 Aditya Konarde'
pagination:
  pagerSize: 5
services:
  googleAnalytics:
    ID: "G-32YZMDJ7FF" 

params:
  profileMode:
    enabled: true
    title: "Aditya Konarde"
    subtitle: "Engineering Leader | Technology Enthusiast | Photographer"
    imageUrl: "images/propic-square.jpeg"
    imageTitle: "Aditya Konarde"
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: "Blog"
        url: "/posts"
      - name: "About"
        url: "/about"
      - name: "Photography"
        url: "https://www.instagram.com/aditya.konarde"
      - name: "Contact"
        url: "https://calendly.com/aditya-konarde"

  socialIcons:
    - name: "linkedin"
      url: "https://www.linkedin.com/in/adityakonarde/"
    - name: "github"
      url: "https://github.com/adityakonarde"
    - name: "instagram"
      url: "https://www.instagram.com/aditya.konarde"

  # Keep your existing params
  defaultTheme: light
  showMenuItems: 4

languages:
  en:
    title: Aditya Konarde's Blog
    params:
      subtitle: ''
      keywords: ''
      menuMore: Show more
      writtenBy: Written by
      readMore: Read more
      readOtherPosts: Read other posts
      newerPosts: Newer posts
      olderPosts: Older posts
      dateFormatSingle: 2006-01-02
      dateFormatList: 2006-01-02
      logo:
        logoText: Aditya Konarde
        logoHomeLink: /
    
    menu:
      main:
      - identifier: Contact
        name: Contact
        url: https://calendly.com/aditya-konarde
      - identifier: about
        name: About
        url: /about
      - identifier: Blog
        name: Blog
        url: /posts
      - identifier: Photography
        name: Photography
        url: https://www.instagram.com/aditya.konarde

